version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.7
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            mkdir -p ./venv
            virtualenv ./venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            python -m unittest

