version: 2
jobs:
  build-py3:
    docker:
      - image: circleci/python:3.6.7
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            mkdir -p ./venv
            virtualenv ./venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m unittest
  build-py2:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            mkdir -p ./venv
            virtualenv ./venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m unittest discover
workflows:
  version: 2
  build_and_test:
    jobs:
      - build-py3
      - build-py2
