version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: virtualenv venv -p python3
      - run: source venv/bin/activate
      - run: python -m unittest
